name-template: "statistics-v$RESOLVED_VERSION" # template 이름 형식
tag-template: "statistics-v$RESOLVED_VERSION"
tag-prefix: statistics-v # 릴리즈 노트 tag prefix(dekstop의 릴리즈 노트이므로 dekstop을 prefix로 함)
template: |
  ## Changes
  $CHANGES
sort-by: "title"
include-labels: # PR의 라벨에 dekstop이 포함된 경우 릴리즈 노트에 포함
  - "statistics"
version-resolver:
  minor:
    labels:
      - "minor"
  default: minor
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"