rootProject.name = "INFO_v2_Backend"
include ("common")
include ("user")
include ("board")
include ("employment")
include ("notice")
include ("email")
include ("comment")
include ("company")
include ("applies")
include ("file")
include ("apiGateway")
include ("eureka")
include ("commonEntity")
include ("auth")