spring:
  application:
    name: auth-service
  datasource:
    url: ${dbDefaultUrl}
    username: ${dbDefaultUsername}
    password: ${dbDefaultPw}
    driver-class-name: ${dbDefaultDriver}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: info
      auto-offset-reset: latest


server:
  port: 0

kafka:
  kafkaServerAddress: localhost:9092

jwt:
  secretKey: dafdsvdavads
  accessExpiredAt: 86400
  refreshExpiredAt: 604800