#spring:
#  config:
#    import: ${SPRING_CONFIG_IMPORT}
#  cloud:
#    config:
#      name: notice
#      profile: default
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: notice-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  datasource:
    hikari:
      idle-timeout: 1000
      max-lifetime: 1825
    url: jdbc:mysql://localhost:3306/info
    username: root
    password: b879645050817!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: info
      auto-offset-reset: latest

server:
  port: 0
eureka:
  instance:
    # 표기되는 규칙 변경
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
kafka:
  kafkaServerAddress: notice:9092

feign:
  client:
    config:
      FileFeignClient:
        connectTimeout: 10000
        readTimeout: 20000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, prefresh
